---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - templates.weave.works
  resources:
  - gitopssets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.weave.works
  resources:
  - gitopssets/finalizers
  verbs:
  - update
- apiGroups:
  - templates.weave.works
  resources:
  - gitopssets/status
  verbs:
  - get
  - patch
  - update
