---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitrepositories-demo-role
rules:
- apiGroups:
  - "source.toolkit.fluxcd.io"
  resources:
  - gitrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitrepositories-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitrepositories-demo-role
subjects:
- kind: ServiceAccount
  name: gitopssets-controller-manager
  namespace: gitopssets-system
